GET http://localhost:8081/rest/payment/getEntities
Content-Type: text/html
Content-Encoding: utf-8

> {%
client.test("Request executed successfully", function() {
  client.assert(response.body === "Hello World from rest service! Response: List is empty", "WORK");
});
%}

###